#!/bin/bash
if [ -z "$1" ]; then
    echo synopsis: $0 classname
    echo Leave out 'Test' suffix
    exit
fi
TESTFILE=tests/integration/$1Test.php
CLASSNAME=$1Test
cat << TXT > $TESTFILE
<?php

class $CLASSNAME extends IntegrationCase {

}
TXT
echo $TESTFILE
vi $TESTFILE
