#!/bin/bash
[ -z "$1" ] && echo "$0 pagename (met .php) <test-path>  # test path defaults to integration test" && exit
[ ! -f "$1" ] && echo "pagename $1 bestaat niet" && exit
PAGE=$1
PAGEFILE=$(basename $PAGE)
DEFAULT=tests/integration/${PAGEFILE%.php}Test.php
TEST=${2:-$DEFAULT}
ALSO=
if [ ! -f "$TEST" ]; then
    CLASS=$(basename $TEST)
    TESTCLASS=${CLASS%.php}
    ALSO=tests/integration/ControllersTest.php
    cat <<TXT > $TEST
<?php

class $TESTCLASS extends IntegrationCase {

    public function test_get() {
        \$this->get('/$PAGEFILE', [
            'ingelogd' => 1,
        ]);
        \$this->assertNoNoise();
    }

}
TXT
fi
tmux split-window -h -l80 "cover-include none; cover-include $PAGE; cover on; ./watcher $TEST"
vi -o $ALSO $TEST $PAGE
