#!/bin/bash
[ "$1" == "" ] && echo Provide a failing seed && exit
vendor/bin/phpunit --order-by=random --random-order-seed=$1 --debug | grep "Test '.*::.*' started" | sed -E "s/.*Test '([^']+)' started.*/\1/" > tests.list
