#!/bin/bash

RUNNER='scripts/suite'

DIRS='./'

watch() {
    clear
    $@
    while inotifywait -q --exclude "\.swp|log*|vendor|\.actual|\.cache" -e modify,close_write --recursive $DIRS; do
        clear
        $@
    done
}

watch $RUNNER $*
